title: Homelab
theme: dark
color: slate
headerStyle: clean
layout:
  Media:
    style: row
    columns: 4
  Photos & Music:
    style: row
    columns: 2
  Home:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
